main/urls.py
from django.urls import include,path
from django.conf.urls import url
from . import views

app_name='main'

urlpatterns = [
    path('',views.index,name='index'),
    path('logout/',views.logout_view,name='logout'),
    path('login/', views.login_view, name='login'),
    path('signup/',views.signup,name='signup'),
    path('newpost/',views.newpost_view,name='newpost'),
    path('postcomment/',views.newcomment_view,name='postcomment'),
    path('deletecomment/',views.deletecomment_view,name='deletecomment'),
    path('deletepost/',views.deletepost_view,name='deletepost'),
    path('follow/',views.follow_view,name='follow'),
    path('<str:name>/',views.userpage,name='userpage')
]

network/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.contrib.auth.models import AbstractUser,AbstractBaseUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

# Create your models here.

# User/profile model, contains additional information from the default user
class User(AbstractUser):
    full_name = models.CharField(max_length=255, blank=True, null=True)
    bio = models.CharField(max_length=150, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to='media/%Y/%m/%d',default='main/static/main/defaultavatar.png')
    following = models.ManyToManyField("User", blank=True, related_name="followers")
    def __str__(self):
        return f"User {self.username}"

# Post model that has owner,likes,location,etc. fields
class Post(models.Model):
    image = models.ImageField(upload_to='media/%Y/%m/%d',blank=False)
    text = models.CharField(max_length=2200)
    location = models.CharField(max_length=100, blank=True)
    date = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    likes = models.ManyToManyField(User, blank=True, related_name="likedposts")

    def __str__(self):
        return f"Post from {self.owner.first_name} at {self.location}"

class CommentManager(models.Manager):
    def create_comment(self,post,owner,text):
        comment = self.create(post=post,owner=owner,text=text)
        return comment

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    text = models.CharField(max_length=1600)
    
    objects = CommentManager()

    def __str__(self):
        return f"Comment from {self.owner.username} on {self.post}"

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

from django.contrib.auth import get_user_model
User = get_user_model()

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image','text','location']

main/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from django.utils.encoding import force_bytes,force_text
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout

from main.forms import SignUpForm,PostForm
from main.tokens import account_activation_token
from .models import *

import datetime
import time

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

# Home page
def index(request):
    if request.user.is_authenticated:
        is_guest = 0
    else:
        is_guest = 1

    return render(request,"main/index.html",{
        "users": User.objects.all(),
        "posts": Post.objects.all().order_by('-date'),
        "is_guest": is_guest
    })

# Sign up page
def signup(request):
    # If the form had errors or something resubmit
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your Network Account'
            message = render_to_string('user/accountactivation.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return HttpResponseRedirect(reverse("user:account_activation_sent"))
    else:
        form = SignUpForm()
    # If you're visiting normally return a blank form
    return render(request, "main/signup.html", {'form': form})



def login_view(request,liking=0):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if liking == 1:
            return render(request, "main/login.html", {
                "message": "Log in to like a post."
            })
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("main:index"))
        else:
            return render(request, "main/login.html", {
                "message": "Invalid credentials."
            })
    return render(request, "main/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("main:index"))

def newpost_view(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        form.instance.owner = request.user
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("main:index"))
    else:
        form = PostForm()
    return render(request, "main/newpost.html", {'form': form})

def newcomment_view(request):
    if request.method == "POST":
        text = request.POST.get("text")
        owner = request.user
        post = Post.objects.get(pk=request.POST.get("post"))
        c = Comment.objects.create_comment(post,owner,text)
        c.save()
        return HttpResponseRedirect(reverse("main:index"))
    else:
        return render(request, "main/index.html")

def deletecomment_view(request):
    if request.method == "POST":
        Comment.objects.get(pk=request.POST.get("comment")).delete()
        return HttpResponseRedirect(reverse("main:index"))
    else:
        return render(request, "main/index.html")

def deletepost_view(request):
    if request.method == "POST":
        Post.objects.get(pk=request.POST.get("post")).delete()
        return HttpResponseRedirect(reverse("main:index"))
    else:
        return render(request, "main/index.html")

def follow_view(request):
    if request.method == "POST":
        if request.POST.get("f") == "0":
            person = User.objects.filter(id=request.POST.get("person")).get()
            person.followers.add(request.user)
            return HttpResponseRedirect(reverse("main:userpage",kwargs={'name':person.username}))
        else:
            person = User.objects.filter(id=request.POST.get("person")).get()
            person.followers.remove(request.user)
            return HttpResponseRedirect(reverse("main:userpage",kwargs={'name':person.username}))
    else:
        return render(request, "main/index.html")

def userpage(request,name):

    try:
        pageuser = User.objects.get(username=name)
        message = 0
        posts = Post.objects.all().filter(owner=pageuser).order_by('-date')

        if request.user.is_authenticated:
            is_guest = 0
            if pageuser in request.user.following.all():
                is_following = 1
            else: 
                is_following = 0
        else:
            is_guest = 1
            is_following = 0
        
    except Exception:
        if request.user.is_authenticated:
            is_guest = 0
        else:
            is_guest = 1
        is_following = 0
        
        pageuser = None
        posts = None
        message = 1

    

    return render(request,"main/userpage.html",{
        "is_guest" : is_guest,
        "pageuser" : pageuser,
        "message" : message,
        "users" : User.objects.all(),
        "posts" : posts,
        "is_following" : is_following
    })

main/templates/main/index.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <title>Network</title>
{% endblock %}

{% block topnav %}
    <div class="topnetwork">
        <a href="{% url 'main:index' %}">Network</a>
    </div>
    <input type="text" class="search-box" placeholder="search">
        {% if is_guest == 1 %}
        <div class="topnetwork">
            <a href="{% url 'main:login' %}">Login</a>
            <a href="{% url 'main:signup' %}">Sign Up</a>
        </div>
            
        {% else %}
        <div class="topnetworkb">
            <a href="{% url 'main:newpost' %}">New Post</a>
            <a href="{% url 'main:logout' %}">Log Out</a>
            <a id="iconwrap" href="{% url 'main:userpage' request.user.username %}"><img id="icon" src="{{ request.user.avatar.url }}" alt="Your Profile"></a>
        </div> 
        {% endif %}

{% endblock %}

{% block body %}
<div class='wrapper'>
    {% for post in posts %}
        <div class="postwrapper">
            <div class="postdesc"><a href="{% url 'main:userpage' post.owner.username %}"><img class="avatarpost" src="{{ post.owner.avatar.url }}" alt="{{ post.owner.full_name }}'s Avatar">
                <div class="postdesctext">
                    <div id="usernamepost">{{ post.owner.username }}</div> 
                </a>
                    {% if post.location %}
                        is at {{ post.location }} on {{ post.date }}
                    {% else %}
                        posted on {{ post.date }}
                    {% endif %}
                </div>
            </div>
            <div id="pimwrap">
                <img id="postimage" src="{{ post.image.url }}" alt="image">
            </div>
            <div class="posttext">
                {{ post.text }}
                {% if request.user == post.owner %}
                <span class="deletebutton">
                    <form action="{% url 'main:deletepost' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="post" value="{{ post.id }}">
                        <input type="submit" value="Delete" style="color: red;" class="deletebutton">
                    </form>
                </span>
                {% endif %}
            </div>
            <button onclick = "toggleComments{{ forloop.counter }}()">Toggle Comment Section</button>
            <div id = "comments{{ forloop.counter }}" style="display: none;">
                {% for comment in post.comments.all %}
                <div class="commenttext">
                    <a href="{% url 'main:userpage' comment.owner.username %}" style="text-decoration: none; color: black;">
                    <img class="commentavatar" src="{{ comment.owner.avatar.url }}" alt="">
                <span class="spancomment">
                    <b>{{ comment.owner.username }}:</b>
                </a>
                    {{ comment.text }}
                </span> 
                {% if request.user == comment.owner %}
                <span class="deletebutton">
                    <form action="{% url 'main:deletecomment' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="comment" value="{{ comment.id }}">
                        <input type="submit" value="Delete" style="color: red;">
                    </form>
                </span>
                {% endif %}
                </div>  
                
                {% endfor %}
                <form action="{% url 'main:postcomment' %}" method="post">
                    {% csrf_token %}
                    <input type="text" name="text" placeholder="Enter a comment...">
                    <input type="hidden" name="post" value="{{ post.id }}">
                    <input type="submit" value="Post"> 
                </form>

            </div>

            <script>
                function toggleComments{{ forloop.counter }}() {
                    var x = document.getElementById("comments{{ forloop.counter }}");
                    if (x.style.display === "none") {
                        x.style.display = "block";
                    } else {
                        x.style.display = "none";
                    }
                }
            </script>

        </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="/static/main/styles.css?version=3" />
        {% block head %}
        {% endblock %}
    </head>

    <body>
        <nav class="topnav">
            <div class="topnav-wrapper">
                {% block topnav %}
                {% endblock %}
            </div>
        </nav>
        <div class=empty></div>
        {% block body %}
        {% endblock %}
    </body>
</html>

main/templates/main/login.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="/static/main/styles.css">
        <title>Login</title>
    </head>

    <body>
        <div class = "loginwrapper">
            <div class = "logincontent">
                <div class = "loginheader">
                    Network
                </div>
                    {% if message %}
                        <div style="color: red;">{{ message }}</div>
                    {% endif %}
                    <form action="{% url 'main:login' %}" method="post">
                        {% csrf_token %}
                        <input type="text" name="username" placeholder="Username" class="loginform">
                        <input type="password" name="password" placeholder="Password" class="loginform">
                        <input type="submit" value="Log In" class="loginbutton">
                </div>
            </div>
        </div>
    </body>
</html>

main/templates/main/newpost.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="/static/main/styles.css">
        <title>New Post</title>
    </head>

    <body>
        <div class = "loginwrapper">
            <div class = "logincontent">
                <div class = "loginheader">
                    New Post
                </div>
                    {% if message %}
                        <div style="color: red;">{{ message }}</div>
                    {% endif %}
                    <form action="{% url 'main:newpost' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="loginform">
                        {{ form.as_p }}
                        </div>
                        <input type="submit" value="Post" class="loginbutton">
                </div>
            </div>
        </div>
    </body>
</html>

main/templates/main/signup.html
{% extends 'main/layout.html' %}

{% block head %}
<title>Sign Up · Network</title>
{% endblock %}

{% block body %}
<h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

main/templates/main/userpage.html
{% extends "main/layout.html" %}

{% block head %}
    <title>{{ pageuser.username }}'s Page</title>
{% endblock %}

{% block topnav %}
    <div class="topnetwork">
        <a href="{% url 'main:index' %}">Network</a>
    </div>
    <input type="text" class="search-box" placeholder="search">
        {% if is_guest == 1 %}
        <div class="topnetwork">
            <a href="{% url 'main:login' %}">Login</a>
            <a href="{% url 'main:signup' %}">Sign Up</a>
        </div>
            
        {% else %}
        <div class="topnetworkb">
            <a href="{% url 'main:newpost' %}">New Post</a>
            <a href="{% url 'main:logout' %}">Log Out</a>
            <a id="iconwrap" href="{% url 'main:userpage' request.user.username %}"><img id="icon" src="{{ request.user.avatar.url }}" alt="Your Profile"></a>
        </div> 
        {% endif %}
{% endblock %}

{% block body %}

{% if message == 0 %}

<div class="toppart">
    <div class="pageuseravatar"> 
        <img src="{{ pageuser.avatar.url }}" alt="">
    </div>
    <div class="t44o3">
        {% if pageuser == request.user %}
            <span class="c34j3">
                {{ pageuser.username }}
            </span>
        {% else %}
            {% if is_following == 1 %}
                <form action="{% url 'main:follow' %}" method="post">
                    {% csrf_token %}
                <span class="c34j3">
                    {{ pageuser.username }}
                </span>
                <input type="hidden" value="{{ pageuser.id }}" name="person">
                <input type="hidden" value="1" name="f">
                <input type="submit" value="Following" class="t4221">
                </form>
            {% else %}
                <form action="{% url 'main:follow' %}" method="post">
                    {% csrf_token %}
                <span class="c34j3">
                    {{ pageuser.username }}
                </span>
                <input type="hidden" value="{{ pageuser.id }}" name="person">
                <input type="hidden" value="0" name="f">
                {% if is_guest == 0 %}
                    <input type="submit" value="Follow" class="t4220">
                {% else %}
                    <a href="{% url 'main:login' %}" class="t4220" style="text-decoration: none;">Follow</a>
                {% endif %}
                </form>
            {% endif %}
        {% endif %}

        <div class="j51k3">

            {% if posts.count == 1 %}
            <b>                 
                {{ posts.count }} 
            </b> Post
            {% else %}
            <b>                 
                {{ posts.count }} 
            </b> Posts
            {% endif %}
             &nbsp;&nbsp;&nbsp; 
             
             
             {% if pageuser.followers.count == 1 %}
             <b>                 
                 {{ pageuser.followers.count }} 
             </b> Follower
             {% else %}
             <b>                 
                 {{ pageuser.followers.count }} 
             </b> Followers
             {% endif %}
             &nbsp;&nbsp;&nbsp; 

             <b> {{ pageuser.following.count }} </b> Following
        </div>
        <div class="j51k3">
            <div>
                <b> {{ pageuser.full_name}} </b>
            </div>
            <div>
                {{ pageuser.bio }}
            </div>
        </div>
    </div>  
</div>
<hr style="width: 80%; margin: auto;">
<div class="bottompart">
    {% for post in posts %}
        <div class = "pagepost">
            <img src="{{ post.image.url }}" alt="">
        </div>
    {% endfor %}

</div>

{% else %}

    <div class="toppart" style="text-align: center; font-family: 'Times New Roman', Times, serif; font-size: 30px;"> Sorry, that user does not exist. </div>

{% endif %}

{% endblock %}